services:
  database:
    container_name: recipe-database
    image: bitnami/postgresql
    user: root
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=recipe
    volumes:
      - recipe-database:/bitnami/postgresql
    networks:
      - recipe
  pgadmin:
    container_name: recipe-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - recipe-pgadmin:/var/lib/pgadmin
    ports:
      - "5051:80"
    networks:
      - recipe
    restart: unless-stopped
networks:
  recipe:
    driver: bridge
volumes:
  recipe-database:
  recipe-pgadmin:
