spring:
  datasource:
    url: jdbc:postgresql://database:5432/recipe
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
server:
  port: 8080